language: node_js
node_js:
  - "12"

cache:
  directories: 
    - node_modules
    - ~/.npm

script:
  - yarn build

deploy:
  provider: pages 
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy del proyecto"
  on:
    branch: main
