language: node_js
node_js:
  - "12"

cache:
  directories: 
    - node_modules
    - ~/.npm

git:
  depth: 3

script:
  - yarn build

notification:
  slack: anonimosas:OCUCxE1g7epy4Dcit7dXsnHV
  email:
    recipients: 
      - desarrolloandbar@gmail.com
      - andreurz@outlook.com
    on_success: always
    on_failure: always
  
deploy:
  provider: pages 
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy del proyecto"
  on:
    branch: master
